### ISSUE TITLE
Estandarizar mayúsculas para indicar opciones. el input recibido pasarlo a minúscula

### ISSUE THREAD

**Issue by lauchacarro** [lic-informatica-umet/Eibu-s-code#1]
https://github.com/lic-informatica-umet/Eibu-s-code/blob/f97304bd929a185adf687e8361f01bf78dba68d0/Uni%20Programacion/IntroProg/Unidad%207%20ejercicios%20conbinados/8.py#L113

**Comment by RavenEibu** [comment]
En el proximo commit de los ejercicios combinados voy a aplicar el fix, si queres hacete un fork y mostrame tu implementacion.
